### ISSUE TITLE
MySQL Client Missing

### ISSUE THREAD

**Issue by joesixpack** [coincubellc/coincube#2]
![image](https://user-images.githubusercontent.com/23145642/66063885-262d3f80-e4f9-11e9-8c5e-f2e24ff3db15.png)

**Comment by garner007** [comment]
edit the Dockerfile's and update mysql-client to default-mysql-client

**Comment by joesixpack** [comment]
That fixed that, but now this:

![image](https://user-images.githubusercontent.com/23145642/66157718-3ae10480-e5d9-11e9-9967-62ee711bcff4.png)

**Comment by robertwilliamallen** [comment]
@joesixpack @garner007 I just pushed an update removing mysql-client. I just built all from scratch here with no errors. Please pull down latest and try again. @joesixpack Looks like the issue on this second attempt broke at `conda: not found` and I'm not sure why that occurred. Let's see if this update solves that issue as well.

**Comment by garner007** [comment]
> @joesixpack @robertwilliamallen - this Conda issue appears to possibly be an issue with the continuumio/anaconda3 container and entrypoints.  https://github.com/ContinuumIO/docker-images/issues/152

**Comment by robertwilliamallen** [comment]
@joesixpack @garner007 Okay, I set to continuumio/anaconda3:2019.03 build and it seems to be working. I think I didn't see this error because I already had an older anaconda container so my computer didn't pull down the latest broken version. Let me know if you can get things running now after you pull down my last commit.

**Comment by garner007** [comment]
@robertwilliamallen - one spot left, in the exapi dockerfile that needs to be updated as well.  Otherwise, looking good.  Thanks.

**Comment by robertwilliamallen** [comment]
@garner007 Ah, yes, forgot about that one. Thanks. Just updated.

**Comment by joesixpack** [comment]
Trying it out now.  Is Anaconda absolutely necessary?  It's 1.57Gb for one pull alone.  Wouldn't Miniconda work?

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/66207256-2cd9c500-e667-11e9-8ab4-c4bde2792f32.png)

![image](https://user-images.githubusercontent.com/23145642/66207292-47ac3980-e667-11e9-9672-b6c5b9b55a7d.png)

**Comment by robertwilliamallen** [comment]
> Trying it out now. Is Anaconda absolutely necessary? It's 1.57Gb for one pull alone. Wouldn't Miniconda work?

It might. I'll see about switching that out.

**Comment by robertwilliamallen** [comment]
@joesixpack Your build is failing on `exapi`?

**Comment by garner007** [comment]
@robertwilliamallen - yes, there is something broken in the linking to exapi.  The submodule update can't find it

**Comment by robertwilliamallen** [comment]
@joesixpack @garner007 Okay, I have updated to miniconda for these three submodules (back-end, cron-job, exapi) and also attached exapi so that should work now. We'll get there...

**Comment by robertwilliamallen** [comment]
@joesixpack @garner007 Hey gentlemen, not sure if you've had time to get things running on your end. I did find and fix an edge-case where encrypted API keys were too long for the allotted space in the database (was 400 chars and I increased to 1000). So, you'll want to pull down and use the latest code to ensure that you don't run into issues adding API keys. Also, if you already built the database you can either manually increase the key and secret lengths in the `api_connections` table or just delete the Docker volumes and build again: https://github.com/Radu-Raicea/Dockerized-Flask/wiki/%5BDocker%5D-Remove-all-Docker-volumes-to-delete-the-database

**Comment by garner007** [comment]
@robertwilliamallen  - thanks.  I have actually had problems getting the API to connect to Poloniex.  This may fix that.

**Comment by robertwilliamallen** [comment]
@garner007 yes, as long as you have updated the database I believe you should be good to go. Please keep me posted.

**Comment by garner007** [comment]
looks like we are cooking with gas, with the change to the column sizes.
