### ISSUE TITLE
EXAPI path not found with submodule update

### ISSUE THREAD

**Issue by garner007** [coincubellc/coincube#3]
Last fix of the "exapi" broke the submodule link

![2019-10-03_20-41-49](https://user-images.githubusercontent.com/4197488/66173499-73ef9800-e61e-11e9-8734-e1294554bdbc.png)

**Comment by robertwilliamallen** [comment]
@garner007 This should be fixed now. Please pull again and try to build.

**Comment by garner007** [comment]
Clean pull and build now

![image](https://user-images.githubusercontent.com/4197488/66239262-69d5a400-e6c7-11e9-9180-e63b2ebfd7d8.png)

**Comment by robertwilliamallen** [comment]
Great! Let's see how it looks for you once you start rolling.
