### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by dodol7** [coincubellc/coincube#5]
Hi guys, I face a problem when I running the app. I followed the instructions step by step as exactly stated in https://github.com/coincubellc/coincube. Finally, I manage to use it through 0.0.0.0:8080 and I manage to made an account. However, I stuck in the processing page as shown in the picture 1 below when I try to login to my account,  like forever. I try to refresh the page, but the result is the same. And then, I look at the terminal and found that there is an error **"... could not proxy request /api/account/user from 0.0.0.0:8080 to http://0.0.0.0:443 ... (ECONNRESET)"** as shown in the picture 2. Could you guys help me to resolve this?

Picture 1.
![error_account_user_stuck](https://user-images.githubusercontent.com/57955259/71555390-60599f00-2a5e-11ea-9140-3aa4d3da274e.jpg)

Picture 2.
![error_account_user](https://user-images.githubusercontent.com/57955259/71555467-45d3f580-2a5f-11ea-9921-db84006985d3.jpg)

Btw, I am using Linux Mint 19.3 running on VirtualBox.

**Comment by maynardpa** [comment]
+1 for me as well. It seems like a show stopper at this point. Also, direct database access is lacking proper documentation.

**Comment by robertwilliamallen** [comment]
This has been fixed.
